@baseUrl = http://localhost:3001/api
@testId = 6317c2d61608d26943a96b78

# get all person
GET {{baseUrl}}/persons

###

# get a person by id
# GET {{baseUrl}}/persons/63161ffa417824b36a244b5d
# GET {{baseUrl}}/persons/63152754d4f5b8bbf20479a2
GET {{baseUrl}}/persons/{{testId}}

###
# get a person by id thats not in the database
GET {{baseUrl}}/persons/1

###

# get total count of person saved in the database
GET http://localhost:3001/info

###

# save a person in database
POST {{baseUrl}}/persons
Content-Type: application/json

{
    "name": "Anabell",
    "number":"040-1223334444"
}

###
# test for missing number in the submitted form
POST {{baseUrl}}/persons
Content-Type: application/json

{
    "name": "Testing from vscode REST Client",
    "number":""
}

###

# test for missing name in the submitted form
POST {{baseUrl}}/persons
Content-Type: application/json

{
    "name": "",
    "number":"015-45678994"
}

###
# test delete method
DELETE {{baseUrl}}/persons/{{testId}}

###
# test put method
PUT {{baseUrl}}/persons/{{testId}}
Content-Type: application/json

{
    "name": "ju",
    "number": "00-00-000000"
}